### ISSUE TITLE
Colors?

### ISSUE THREAD

**Issue by aaronfraint** [dvrpc/sidewalk-data-viz#6]
Any thoughts on the colors of the various map layers? What about the basemap?

**Comment by crvanpollard** [comment]
A few suggestions on Basemap:
1) Bring the labels to the top so they draw above the map layers
2) Add highway/route shields (this may require a custom Mapbox style built in Mapbox Studio) 

Map Layers - I'd like to see a wider sidebar (checkout RTSP https://www.dvrpc.org/webmaps/rtsp/#gap/tool). If you can make the legends bigger and have them appear under their layers that would help users identify what all the colors represent. We can chat colors soon

**Comment by aaronfraint** [comment]
I adjusted the map style so that the labels appear on top of everything else. 

RE: Sidebar - changing the class on the `<nav>` element from `col-md-2` to `col-md-3` made it TOO big. Will need to find a better way to resize it.
