### ISSUE TITLE
New feature? -> Search box that will "zoom to"

### ISSUE THREAD

**Issue by aaronfraint** [dvrpc/sidewalk-data-viz#7]
Should we introduce a "zoom to" style search box for counties/municipalities in the region?

**Comment by crvanpollard** [comment]
100% agree that we need one that allows users to type in a search (via Typeahead [https://twitter.github.io/typeahead.js/](https://twitter.github.io/typeahead.js/) ) or it's a drop-down menu but they should select a County first before getting MCD results as listing all 353 MCD is not the best approach.

**Comment by aaronfraint** [comment]
@crvanpollard Do you have any thoughts on other typeahead alternatives? This library seems pretty stale - last committed to in 2015.

**Comment by jstrangfeld** [comment]
Check these docs on geocoding:
https://docs.mapbox.com/help/tutorials/local-search-geocoding-api/

There are a number of libraries listed to implement a place search, in
addition to a full tutorial to add the search box to the map.

**Comment by crvanpollard** [comment]
@aaronfraint nothing off the top of my head but if we use a google maps or mapbox geocoding api we will need to set a bounding box to limit the search parameters so that users don't get zoomed to Ardmore.....Oklahoma or Springfield, MO

**Comment by aaronfraint** [comment]
Added the Mapbox Geocoder with a `bbox` around the 9-county region. Works well and was easy to do. Thanks everyone!
